---
  - name: My machine
    hosts: all

    vars:
      mas_installed_app_ids:
        - 497799835 # Xcode

      homebrew_installed_packages:
        - ssh-copy-id
        - pv

      homebrew_cask_apps:
        - docker
        - firefox
        - google-chrome
        - vlc

    roles:
      - dev
      - geerlingguy.mac.homebrew
      - geerlingguy.mac.mas
